### ISSUE TITLE
which way does the switch go?

### ISSUE THREAD

**Issue by tedder** [redbear/IoT_pHAT#1]
There's no visible traces to indicate what way to set the antenna selector for "onboard". Most of the pictures show the switch in the "away from pin headers" position. Is that the internal?

**Comment by Cheong2K** [comment]
Hi, thank you pointing out this, added to the block diagram already.

**Comment by Cheong2K** [comment]
Hi, does it work for you?

**Comment by impressiver** [comment]
For anyone landing here w/ the same question:

**PCB antenna:** Switch down (away from headers, toward bear logo).  
**External antenna:** Switch up (toward headers, away from bear logo).

**Comment by Cheong2K** [comment]
Thanks @impressiver !
