### ISSUE TITLE
Not working with NOOBS

### ISSUE THREAD

**Issue by procount** [redbear/IoT_pHAT#12]
The IoT_pHAT uses the same brcm43430 wifi chipset as is used in the RPi3 working over SDIO. 
It works fine in Raspbian.
NOOBS can operate with the RPi3 wifi, so it should have the correct wifi driver and firmware files included.
The correct device-tree entries appear in the /proc subsystem for the IoT_pHAT showing that the NOOBS kernel can read the details from the HAT EEPROM (I already upgraded to v0.3).

So why doesn't the wifi appear in NOOBS? 
Is there something missing in the NOOBS kernel that I need to add?

**Comment by Cheong2K** [comment]
We tested with NOOBS 2.0.0, it works fine. Which version are you using?

**Comment by procount** [comment]
Originally I used NOOBS v1.9. I have also tried the latest v2.0. I have tried it with the latest PiZero v1.3 and a Pi2B.
I have started again this morning with a fresh SD card, redownloaded NOOBS v2.0 and installed that to confirm my findings.
In NOOBS, the wifi icon is greyed out.
In the NOOBS rescue shell (ctrl-alt-F2, root/raspberry), ifconfig does not show any wireless adaptors (only eth0 on the Pi2B).
Looking at dmesg output, the brcmfmac driver is registered with the kernel, but it never gets loaded.
The firmware (brcmfmac43430-sdio.bin and brcmfmac43134.bin is present in /lib/firmware/brcm.
cat /proc/device-tree/hat/product = "IoT pHAT w/eep_v0.3".
If I use NOOBS to install Raspbian, Raspbian will happily detect the IoTpHAT and works properly.
Is there any more information I can provide?

**Comment by Cheong2K** [comment]
I know what you mean now.

**Comment by procount** [comment]
Is there any progress in understanding why the IoTpHAT does not work in NOOBS-lite?

**Comment by Cheong2K** [comment]
The RPi team has fixed this and will be ready in NOOBS Lite version 2.1, so stay tuned.

**Comment by procount** [comment]
Thanks.

**Comment by procount** [comment]
IoTpHAT is now supported in my PINN fork of NOOBS as well. https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=142574
