### ISSUE TITLE
Can not get Bluetooth working

### ISSUE THREAD

**Issue by oshank** [redbear/IoT_pHAT#13]
I've tried everything in the issues, I have v0.3 of the eep, the clock is set correctly.

When I run
`sudo hciconfig status`
I get
`Can't open HCI socket.: Address family not supported by protocol`

The Pi is running DietPi if that makes any difference.

**Comment by Cheong2K** [comment]
I suggest you to use Raspbian to test first if this is about hardware problem.

**Comment by oshank** [comment]
I tested this on the newest version of Rasbian and it worked out of the box. Did not need to do anything special. Just pulled up the desktop and wifi and bluetooth were working perfectly.
