### ISSUE TITLE
Wifi keeps disconnecting

### ISSUE THREAD

**Issue by komadori1** [redbear/IoT_pHAT#22]
Hey,
I have recently ordered the IoT pHAT and my wifi keeps disconnecting after a minute of SSH-ing into my Pi. I have tried a different Pi and the same happens. Would you happen to have any input on what I could try to debug what's wrong?

Best Regards

**Comment by Cheong2K** [comment]
Hi, sorry but please post your problem in the support forum or submit a support ticket to RedBear, they will provide technical support for you.
https://redbear.cc/contact-us/
