### ISSUE TITLE
BT not working with latest NOOBS (ver. 2.4.1)

### ISSUE THREAD

**Issue by Cheong2K** [redbear/IoT_pHAT#24]
BT does not work with NOOBS ver. 2.4.1
EEPROM update is required.

**Comment by procount** [comment]
You must be referring to the 21-06-2017 version of Raspbian that is installed by NOOBS v2.4.1, since NOOBS itself does not use BT.

**Comment by Cheong2K** [comment]
@procount , thank you for your information.

**Comment by Cheong2K** [comment]
This has been fixed with updating the EEPROM to v0.5
