### ISSUE TITLE
Shutdown will cause kernel panic

### ISSUE THREAD

**Issue by Cheong2K** [redbear/IoT_pHAT#3]
$ sudo shutdown now

will cause kernel panic, this is also the problem of the content inside the EEPROM, now looking into this issue.

**Comment by Cheong2K** [comment]
the gpio-poweroff overlay causes this problem:
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=137560&p=922461#p922461
and
https://www.raspberrypi.org/forums/viewtopic.php?f=107&t=143519

We make use of GPIO 6 and 5 to reset the wireless module. If you don't stack the IoT pHAT, but add this to the config.txt file, it will cause kernel panic.
dtoverlay=gpio-poweroff,gpiopin=6,active_low=true

**Comment by Cheong2K** [comment]
https://github.com/raspberrypi/linux/wiki/Upstreaming#poweroff

**Comment by bprobbins** [comment]
Any progress on this problem?

**Comment by codersaur** [comment]
I've got this issue, is there a solution yet?

**Comment by codersaur** [comment]
Really need a fix for this too. It's stopping me use the IOT PHAT as I need to be able to reboot the Pi cleanly without physical access.

**Comment by Cheong2K** [comment]
This will be fixed with EEPROM firmware v0.4, stay tuned.

**Comment by Cheong2K** [comment]
https://github.com/redbear/IoT_pHAT/tree/master/eeprom/experimental
Please follow this to update the EEPROM firmware to v0.4

**Comment by codersaur** [comment]
Thanks, it appears to work.
