### ISSUE TITLE
Red bear WiFi hat no longer works

### ISSUE THREAD

**Issue by rivale** [redbear/IoT_pHAT#30]
I have the same problem with red bear WiFi and BT on loading raspbian error 110 SDIO, It was working.
Using pizero with red bear hat.
Pi zero works with a usb WiFi dongle.

**Comment by PowerShellCrack** [comment]
I noticed the same thing using rpi-zero's Debian's Stretch. However its does work with Debian's Jessie. This goes for octoprint's and raspberian OS's  I have tried every driver installer there is. I am unable to get it the wireless or Bluetooth to work. 

Error:
mmc1: error -110 whilst initializing SDIO card
mmc1: error -110 whilst initializing SDIO card

Current OS:
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"


Works with:
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by rivale** [comment]
Hi PowerShellCrack

Managed to get the wireless working using raspian Jessie version 2017/7/5
Bluetooth is still not working but I’m working on it.
Thanks
