### ISSUE TITLE
Doesn't work at all. 

### ISSUE THREAD

**Issue by brightmoon03** [redbear/IoT_pHAT#7]
When I try to turn on the pi with the pHat on the Pi, it won't turn on, but when I try without the hat, it turns on normally. I have a Pi 2 running raspbian and kali Linux. What should I do?

**Comment by brightmoon03** [comment]
If I turn the Pi on, and plug it in, it will just freeze up...

**Comment by Cheong2K** [comment]
Did you try with NOOBS 1.9.2?

**Comment by brightmoon03** [comment]
It now works with the latest version of raspbian. When I try connect to my Magic Mouse and magic keyboard, it never pairs. Also, Is there a way to be able to make it work for kali Linux?

**Comment by Cheong2K** [comment]
Hi, please discuss these in the forum, they will provide technical support to you: discuss.redbear.cc
