### ISSUE TITLE
bluez_ble mac_address AA:AA:AA:AA:AA:AA

### ISSUE THREAD

**Issue by louisnicolas** [redbear/IoT_pHAT#9]
Hi all,

I'am using the board on a PI Zero with QT 5.7.1 and I developped a BLE server.

Everything works well except the mac-address always : AA:AA:AA:AA:AA:AA:AA

I checked with **hciconfig**.

_pi@raspberrypi:~ $ sudo hciconfig status
hci0:   Type: Primary  Bus: UART
        BD Address: **AA:AA:AA:AA:AA:AA**  ACL MTU: 1021:8  SCO MTU: 64:1
        UP RUNNING 
        RX bytes:10266 acl:485 sco:0 events:589 errors:0
        TX bytes:16384 acl:530 sco:0 commands:72 errors:0_

It seems the bluez layer does not find the mac address.
Do you know how I can to set it ?

My Pi is running bluez-5.41 and I updated to firmware of the IoT_pHat.

Thank for your help,
Have a nice day,
Nicolas

**Comment by Cheong2K** [comment]
I think there was something wrong with you, did you run `sudo rpi-update` ?

**Comment by louisnicolas** [comment]
Hi !
Thank you for your answer.
After a rpi-update, I get the mac-address.

Very nice product working fine with QT  5.7 as BLE server :)

**Comment by Cheong2K** [comment]
Great! Please also share how to use QT with the Pi Zero if you can.

**Comment by louisnicolas** [comment]
I prepare a tutorial and I share it :)
